name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t brucevaynerd/weatherforecast_api:latest -f DockerAPITest/Dockerfile
    - name: Push Image to DockerHub
      run: |
       docker login -u brucevaynerd -p ${{ secrets.DOCKER_HUB_TOKEN }}
       docker push brucewaynerd/weatherforecast_api:latest